/**
 * Stripe plan definitions with real price IDs.
 * Price IDs were generated by scripts/setup-stripe.ts in test mode.
 */
export const PLANS = {
  premium: {
    name: 'Premium',
    priceId: 'price_1TCUXkAsOomwt34iwlcVUrGB',
    price: '$9.99',
    period: '/month',
    mode: 'subscription' as const,
    trial: 3,
    features: [
      'Unlimited habits',
      'Advanced analytics',
      'Priority support',
    ],
  },
  diamond: {
    name: 'Diamond',
    priceId: 'price_1TCUXlAsOomwt34iD2TQ8f64',
    price: '$19.99',
    period: '/month',
    mode: 'subscription' as const,
    trial: 3,
    features: [
      'Everything in Premium',
      'AI insights',
      'Custom themes',
      'Team features',
    ],
  },
  lifetime: {
    name: 'Lifetime',
    priceId: 'price_1TCUXmAsOomwt34ibqRnvKOX',
    price: '$79.99',
    period: 'one-time',
    mode: 'payment' as const,
    trial: 0,
    features: [
      'All features forever',
      'All future updates',
      'No recurring charges',
    ],
  },
} as const

export type PlanKey = keyof typeof PLANS
export type Plan = (typeof PLANS)[PlanKey]
